name: build

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:

    runs-on: ubuntu-latest # ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4.1.0
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.8.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
      - name: Lint with ESLint
        run: |
          npm run lint
      - name: Test with Testing Library and generate coverage reports
        run: |
          npm test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3.1.4
