name: build

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:

    runs-on: ubuntu-latest # ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10'
      - name: Install backend
        run: |
          python -m pip install --upgrade pip
          pip install \
          https://github.com/sun1638650145/bunnyburrow-watch2gether-backend/releases/download/v0.1b2/watch2gether-0.1b2-py3-none-any.whl
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
      - name: Lint with ESLint and Stylelint
        run: |
          npm run lint
          npm run stylelint
      - name: Test with Testing Library and generate coverage reports
        run: |
          npm test -- --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.2.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
