name: release

on:
  release:
    types: [ 'published' ]

permissions:
  contents: write

jobs:
  deploy:

    runs-on: ubuntu-latest # ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          npm install
      - name: Build release
        run: |
          npm run build
          version=$(node -p "require('./package.json').version;") # 获取版本号.
          zip -r watch2gether-$version.zip build
      - name: Publish release to Releases
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: |
            *.zip
